#version 450

#define PI 3.141592653

#define SAMPLENUM 1024

/*
input: environment cube map
output: Llm 4x4 map value range(-1,1)
*/
layout(local_size_x=4,local_size_y=1,local_size_z=1)in;

layout(binding=0) uniform sampler2D inImage;
layout(rgba32f,binding=1) uniform image2D outImage;

layout(constant_id=3) const int skyboxWidth=1024;

//===========================
//http://holger.dammertz.org/stuff/notes_HammersleyOnHemisphere.html
float radicalInverse_VdC(uint bits) {
	bits = (bits << 16u) | (bits >> 16u);
	bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
	bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
	bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
	bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
	return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}
vec2 hammersley2d(int i, int N) {
	return vec2(float(i) / float(N), radicalInverse_VdC(uint(i)));
}

mat3 surfaceTBN(vec3 N)
{
	vec3 up=abs(N.z)>0.999?vec3(1,0,0):vec3(0,0,1);
	vec3 T=cross(up,N);
	vec3 B=cross(N,T);
	return mat3(T,B,N);
}
vec3 getCubeTexCoordFromCubeMap(ivec3 st,uint width){
	vec2 uv=vec2(st.xy)*2./float(width)-1.;
	vec3 res;
	switch(st.z){
		case 0: //x+
			res=vec3(1.,-uv.y,-uv.x);
			break;  
		case 1: //x-
			res=vec3(-1.,-uv.y,uv.x);
			break;
		case 2: //y+
			res=vec3(uv.x,1,uv.y);
			break;
		case 3: //y-
			res=vec3(uv.x,-1,-uv.y);
			break;
		case 4: //z+
			res=vec3(uv.x,-uv.y,1.);
			break;
		case 5: //z-
			res=vec3(-uv.x,-uv.y,-1.);
			break;
	}
	return normalize(res);
}

vec2 CubeTexCoord2EquirectangularUV(vec3 cubeTexCoord){
	vec2 uv;
	uv.x=(atan(cubeTexCoord.z,cubeTexCoord.x)+PI)/(2.*PI);  //[0 1]
	uv.y=acos(cubeTexCoord.y)/PI;	//[0,1]
	return uv;
}

//https://developer.nvidia.com/gpugems/gpugems2/part-ii-shading-lighting-and-shadows/chapter-10-real-time-computation-dynamic
float SH_Ylm(vec3 N,int l,int m){
	//p should be normalized
	m+=l;
	if(l==0&&m==0)return 0.282095;
	else if(l==1){
		switch(m){
			case 0:return 0.488603*N.z; //-1
			case 1:return 0.488603*N.y; //0
			case 2:return 0.488603*N.x; //1
		}	
	}else if(l==2){
		switch(m){
			case 0:return 1.092548*N.x*N.z; //-2
			case 1:return 1.092548*N.z*N.y; //-1
			case 2:return 0.315392*(3*N.y*N.y-1.); //0
			case 3:return 1.092548*N.x*N.y; //1
			case 4:return 0.546274*(N.x*N.x-N.z*N.z);   //2
		}
	}
	return 0.;
}

//degree 2
ivec2 getlm2_from_tile4x4(ivec2 st){
	if(st.x>2||st.y>2)return ivec2(-1,0);
	int s=st.y*3+st.x;
	if(s>=4)return ivec2(2,s-6);
	else if(s>=1) return ivec2(1,s-2);
	else return ivec2(0);
}

vec3 Llm(ivec2 lm){
	vec3 col=vec3(0.);

	float l=0.5*log2(float(skyboxWidth*skyboxWidth)/SAMPLENUM);

	#if 1
	for(int i=0;i<SAMPLENUM;++i){
		vec2 xi=hammersley2d(i,SAMPLENUM);
		//theta [0,pi], phi[0,2*pi]
		float cosTheta=1.-2*xi.y;
		float sinTheta=sqrt(1-cosTheta*cosTheta);
		float phi=2.*PI*xi.x;
		vec3 L=vec3(sinTheta*cos(phi),cosTheta,sinTheta*sin(phi));
		float Ylm=SH_Ylm(L,lm.x,lm.y);
		vec2 st=CubeTexCoord2EquirectangularUV(L);
		float pdf=sinTheta;
		float lod=max(l-0.5*log2(pdf),0.);
		col+=textureLod(inImage,st,lod).rgb*Ylm; 
	}
	col/=float(SAMPLENUM);
	col*=4.;
	#else
	int num=0;
	const float STEP=0.1;
	for(float phi=0;phi<2.*PI;phi+=STEP){
		for(float theta=0;theta<PI;theta+=STEP){
			float cosTheta=cos(theta);
			float sinTheta=sin(theta);
			vec3 L=vec3(sinTheta*cos(phi),cosTheta,sinTheta*sin(phi));
			float Ylm=SH_Ylm(L,lm.x,lm.y);
			col+=texture(texCube,L).rgb*Ylm*sinTheta; 
			num+=1;
		}
	}
	col/=num;
	col*=2.*PI;	//pdf is 2.*PI*PI 
	#endif
	return col;
}

void main(){
	ivec2 ij=ivec2(gl_LocalInvocationID.x,gl_WorkGroupID.x);
	if(ij.x>2||ij.y>2)
		return;
	ivec2 lm=getlm2_from_tile4x4(ij);
	vec3 col=Llm(lm)*0.5+0.5;
	imageStore(outImage,ij,vec4(col,1.));
	//imageStore(outImage,ij,vec4(1,0,0,1.));
}